Remove condition that prevent to select same day
uselessdev/datepicker pull request #48
Opened 2022-06-03 21:39 UTC by raphaelrochap

Hey guys! :grin: 

Well, im starting to use this datepicker, and i liked very much, but the component does'nt allow me to choose the sameday in the 'start' and the 'end' props (prop value, actually).

So, this PR suggest to remove the condition that prevent to select the same day.

As argument to do this change, is that even AntDesign and MaterialUI allow to select the same day in your range date pickers.

If it is a significative change to the users of the component, maybe a new prop to this new comportament?

Well, thats it!
Thanks!! :grinning:

2022-06-03 22:05 UTC, uselessdev commented
Hi @raphaelrochap thank you for this PR.

I'm curious about your need to select the same day for `start` and `end`, can you tell me more about your use case, please?

2022-06-04 20:30 UTC, raphaelrochap commented
Hi @uselessdev!

Yeah, of course!
Well, im working in a frontend refactoring of an existing project. It run in AngularJS, and im building a new one, with ReactJS and ChakraUI.

It's a send email application, that have a page for filtering of the sent emails. Currently, the website gives the users, two independent fields, one for `start` date and another to the `end` date. Each one has his own calendar.

And looking for an existing DatePicker component, i found this, and i liked to see in a single calendar the range of the two selected dates. But, for being a filtering of sent email, the user can select in the `start` and `end` the same date.

With the current rules, I'll force the user to select two different dates to see the data of only one of this dates.

That's why I need this change.

2022-06-08 04:35 UTC, uselessdev requested changes

2022-06-08 04:35 UTC, uselessdev commented on src/calendar.tsx
> -    ) {
I think a better approach here should be to add a new prop to the library something like `allowSelectSameDay` with this we don't need to remove this for now.

2022-06-21 09:36 UTC, closed without merging